build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
        run_tests:
                image: python:2-alpine
                commands:
                        - pip install -r requirements.txt
                        - python testing.psh:
    docker:
        repo: tkamata/cicd_demoapp
        tag: latest
        username: tkamata
        password: TK83425kt
        email: teppei.kamata@gmail.com

